#!/bin/sh

exec 2>&1
exec prometheus -config.file=/etc/prometheus/prometheus.yml \
      -storage.local.path=/TivoData/prometheus \
      -web.console.libraries=/etc/prometheus/console_libraries \
      -web.console.templates=/etc/prometheus/consoles